### ISSUE TITLE
ArrayIndexOutOfBoundsException when i enter Space and hit return

### ISSUE THREAD

**Issue by just4phil** [StrongJoshua/libgdx-inGameConsole#2]
it crashes with ArrayIndexOutOfBoundsException when i enter Space and hit return:

Exception in thread "LWJGL Application" java.lang.ArrayIndexOutOfBoundsException: 0
	at com.strongjoshua.console.Console.execCommand(Console.java:265)
	at com.strongjoshua.console.Console.access$3(Console.java:261)
	at com.strongjoshua.console.Console$KeyListener.keyDown(Console.java:410)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:44)

**Comment by StrongJoshua** [comment]
Should be fixed! Thanks for submitting :)
