### ISSUE TITLE
Crashes when log method is called.

### ISSUE THREAD

**Issue by Blunderchips** [StrongJoshua/libgdx-inGameConsole#38]
Crashing with the following exception.

`Exception in thread "LWJGL Application" java.lang.IndexOutOfBoundsException: index can't be >= size: 26 >= 0
	at com.badlogic.gdx.utils.Array.removeIndex(Array.java:260)
	at com.badlogic.gdx.utils.SnapshotArray.removeIndex(SnapshotArray.java:130)
	at com.badlogic.gdx.utils.Array.removeValue(Array.java:243)
	at com.badlogic.gdx.utils.SnapshotArray.removeValue(SnapshotArray.java:125)
	at com.badlogic.gdx.scenes.scene2d.Group.removeActor(Group.java:330)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.removeActor(Table.java:298)
	at com.badlogic.gdx.scenes.scene2d.Actor.remove(Actor.java:216)
	at com.badlogic.gdx.scenes.scene2d.ui.Table.clearChildren(Table.java:310)
	at com.badlogic.gdx.scenes.scene2d.Group.clear(Group.java:357)
	at com.strongjoshua.console.GUIConsole$ConsoleDisplay.refresh(GUIConsole.java:420)
	at com.strongjoshua.console.GUIConsole.log(GUIConsole.java:275)`

This issue can be replicated by logging a lot of messages to the console. I suspect the console is trying to remove a log that has already been removed.

**Comment by StrongJoshua** [comment]
I'll look into this tomorrow. A strange issue.

**Comment by StrongJoshua** [comment]
No follow-up. Closing this issue.
